# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Virtual_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Virtual_UI(object):
    def setupUi(self, Virtual_UI):
        Virtual_UI.setObjectName("Virtual_UI")
        Virtual_UI.resize(1036, 621)
        self.centralwidget = QtWidgets.QWidget(Virtual_UI)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1041, 621))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Git hub Projects or Gits in Python//Gui-Based Virtual Assistant_ PROGRESSIVE//Black and Blue Simple Technology Business Plan Presentation.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(650, 490, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(0, 0, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:4px;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(760, 490, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);\n"
"border-radius:4px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(660, 110, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(510, 60, 471, 321))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Git hub Projects or Gits in Python//Gui-Based Virtual Assistant_ PROGRESSIVE//joinblink-blink-unscreen.gif"))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(510, 320, 481, 181))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("Git hub Projects or Gits in Python/Gui-Based Virtual Assistant_ PROGRESSIVE//microphone-ui-animation-unscreen.gif"))
        self.label_4.setObjectName("label_4")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(60, 20, 210, 51)) #date-time browser label
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background:transparent;\n"
"border-radius:none;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(240, 20, 141, 51)) #date-time browser label
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet("background: transparent;\n"
"border-radius:none;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(730, -120, 301, 351))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("Git hub Projects or Gits in Python//Gui-Based Virtual Assistant_ PROGRESSIVE//pngtree-neon-frame-design-material-png-image_4413994-removebg-preview.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        Virtual_UI.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Virtual_UI)
        self.statusbar.setObjectName("statusbar")
        Virtual_UI.setStatusBar(self.statusbar)

        self.retranslateUi(Virtual_UI)
        QtCore.QMetaObject.connectSlotsByName(Virtual_UI)

    def retranslateUi(self, Virtual_UI):
        _translate = QtCore.QCoreApplication.translate
        Virtual_UI.setWindowTitle(_translate("Virtual_UI", "MainWindow"))
        self.pushButton.setText(_translate("Virtual_UI", "Start"))
        self.pushButton_2.setText(_translate("Virtual_UI", "Stop"))
        self.label_2.setText(_translate("Virtual_UI", ""))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Virtual_UI = QtWidgets.QMainWindow()
    ui = Ui_Virtual_UI()
    ui.setupUi(Virtual_UI)
    Virtual_UI.show()
    sys.exit(app.exec_())
